---
title: "Career Planning As Discussed in Jeff Leek's How to Be a Modern Scientist"
author: "Toni Shoyinka"
date: last-modified
description: "A review of Jeff Leek's book with key takeaways for career planning in science."
---

I wanted to look into the “How to Be A Modern Scientist” chapter regarding Career Planning. Though that particular chapter is aimed towards graduate and postdoc students, I thought it would be an interesting thing to start looking into. I’m about a year away from finishing my undergrad program, so I’ve started to get a lot of questions about my next steps. This put into context some aspects of entering the workforce that I never considered before.

Leek mentions the potential detriment of scientific career aspirations driven by altruism: a reduced focus on the career planning and development aspect of entering such a field. At first, I wasn’t sure I agreed. All the students I know who are aspiring to go into science have pretty good ideas of what it is that they want to do. They want to do research, they want to teach, they want to go into industry. However, the more I thought about what Leek was saying, the more I realized that these aspirations were surface-level. When asked about the specifics, students (myself included) begin to flounder and people immediately placate with “it’s okay if you don’t know yet” or “you’ve still got plenty of time”. 

We’re perfectly content with people saying they’re going into science and having no clue what that’s supposed to look like because it’s been viewed (from the outsider’s perspective) as a protected class of employment in a way. We’ll always need scientists and researchers and professors, so as long as you have the education to become one, you’ll be fine. This does up-and-coming scientific professionals a disservice. Having no career trajectory mapped out, no back-up plan, and no safety net leaves them susceptible to the changing tides of the market. Do you want to work as a tenure track professor at a research institution or at a liberal arts school? Are you more comfortable working a “hard money” job or a “soft money” one? This is especially relevant in a time like this when funding and associated factors are not as secure as they once were. 

Encouraging students, even as early as undergrad, to start asking themselves the questions Leek provides in his Career Planning chapter will make a world of difference in the way the next generation of scientists enter the workforce and learn to advocate for themselves. Knowing what you want and how you want to get it is something that my parents taught me to prioritize early in my life, so seeing it contextualized in this way, in this field that I don’t have as much guidance in, has been incredibly influential. I’m definitely going to fill out the planning worksheet provided and start asking myself questions.
